server:
  port: 8080
  servlet:
    context-path: /api

# WebSocket Configuration
websocket:
  allowed-origins:
    - http://localhost:3000    # React dev server
    - http://localhost:5173    # Vite dev server
    - http://127.0.0.1:3000
    - http://127.0.0.1:5173
  endpoint: /ws/game
  message-size-limit: 65536    # 64KB max message size

# Core Server Connection
core:
  host: localhost
  port: 5000
  connection-pool:
    max-connections: 10
    connection-timeout: 5000   # 5 seconds
    read-timeout: 30000       # 30 seconds
  heartbeat:
    interval: 30000           # 30 seconds
    timeout: 10000            # 10 seconds

# Security Configuration
security:
  rate-limiting:
    enabled: true
    default-limit: 30         # requests per minute
    auth-limit: 5            # login attempts per minute
    game-limit: 60           # game actions per minute
  cors:
    enabled: true
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    max-age: 3600

# Logging Configuration
logging:
  level:
    com.n9.gateway: DEBUG
    org.springframework.web.socket: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{userId},%X{sessionId}] %logger{36} - %msg%n"
  file:
    name: logs/gateway.log
    max-size: 100MB
    max-history: 30

# Actuator for Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Application Info
info:
  app:
    name: Card Game Gateway
    version: @project.version@
    description: WebSocket Gateway for Card Game
  build:
    time: @maven.build.timestamp@