// Hằng số thông điệp giao tiếp với backend
// Dùng: import { MT } from "../protocol/mt";

export const MT = {
  AUTH_LOGIN_REQUEST: 'AUTH.LOGIN_REQUEST',
  AUTH_LOGIN_OK: 'AUTH.LOGIN_OK',
  AUTH_LOGIN_FAIL: 'AUTH.LOGIN_FAIL',

  LOBBY_SNAPSHOT: 'LOBBY.SNAPSHOT',
  LOBBY_UPDATE: 'LOBBY.UPDATE',

  MATCH_REQUEST: 'MATCH.REQUEST',
  MATCH_CANCEL: 'MATCH.CANCEL',
  MATCH_FOUND: 'MATCH.FOUND',
  MATCH_START: 'MATCH.START',

  GAME_ROUND_START: 'GAME.ROUND_START',
  GAME_PLAY_CARD: 'GAME.PLAY_CARD',
  GAME_PICK_ACK: 'GAME.PICK_ACK',
  GAME_PICK_NACK: 'GAME.PICK_NACK',
  GAME_OPPONENT_STATUS: 'GAME.OPPONENT_STATUS',
  GAME_ROUND_REVEAL: 'GAME.ROUND_REVEAL',

  MATCH_RESULT: 'MATCH.RESULT',
  MATCH_OPPONENT_LEFT: 'MATCH.OPPONENT_LEFT',

  LEADERBOARD_REQUEST: 'LEADERBOARD.REQUEST',
  LEADERBOARD_RESPONSE: 'LEADERBOARD.RESPONSE',

  SYS_PING: 'SYS.PING',
  SYS_PONG: 'SYS.PONG',
  SYS_ERROR: 'SYS.ERROR',
};

export default MT;


